### ISSUE TITLE
Registry configuration 

### ISSUE THREAD

**Issue by mijos** [hovu96/splunk_as_a_service_app#18]
The splunk-as-a-service-app is trying to pull images from the internet, which is not possible for air gapped deployments. I need a way to specify the server to pull from.

**Comment by hovu96** [comment]
Commit c36d40a7b50ec6d12ebcc292927ed81b5d6a087f closes this. In the cluster settings, you can now specify the Splunk image to use. That way you can specify which Splunk version to use, but also specify the image repository to get the image from. Full format `hostname[:port]/username/reponame[:tag]`
